import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ParticleBackground from "@/components/ParticleBackground";
import { motion } from "framer-motion";

import business1 from "@/assets/thumbnails/business-1.jpg";
import business2 from "@/assets/thumbnails/business-2.jpg";
import business3 from "@/assets/thumbnails/business-3.jpg";
import business4 from "@/assets/thumbnails/business-4.jpg";
import business5 from "@/assets/thumbnails/business-5.jpg";
import business6 from "@/assets/thumbnails/business-6.jpg";
import business7 from "@/assets/thumbnails/business-7.jpg";
import business8 from "@/assets/thumbnails/business-8.jpg";
import business9 from "@/assets/thumbnails/business-9.jpg";
import business10 from "@/assets/thumbnails/business-10.jpg";

interface ThumbnailSection {
  title: string;
  thumbnails: { src: string; alt: string }[];
}

const sections: ThumbnailSection[] = [
  {
    title: "Business",
    thumbnails: [
      { src: business1, alt: "Copy Me - Business Growth" },
      { src: business2, alt: "Email Marketing Strategy" },
      { src: business3, alt: "Photoshop Skills" },
      { src: business4, alt: "10X More Clients" },
      { src: business5, alt: "Money Strategies" },
      { src: business6, alt: "Multiple Income Streams" },
      { src: business7, alt: "Best AI Tools 2025" },
      { src: business8, alt: "$0 to $10M Journey" },
      { src: business9, alt: "Trading Profit" },
    ],
  },
];

const Examples = () => {
  return (
    <div className="min-h-screen overflow-x-hidden relative">
      <ParticleBackground />
      <div className="relative z-10">
        <Navbar />
        <div className="pt-24 pb-16 container mx-auto px-4">
          <motion.div
            className="text-center mb-12"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <h1 className="font-display text-4xl md:text-6xl font-extrabold tracking-tight gradient-text mb-4">
              Thumbnail Examples
            </h1>
            <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
              Every thumbnail below was generated by AntiGeneric AI.
            </p>
          </motion.div>

          {sections.map((section, sIdx) => (
            <motion.div
              key={section.title}
              className="mb-16"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: sIdx * 0.1 }}
            >
              <h2 className="font-display text-2xl md:text-3xl font-bold gradient-text mb-6 text-center">
                {section.title}
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {section.thumbnails.map((thumb, i) => (
                  <motion.div
                    key={i}
                    className="rounded-xl overflow-hidden card-nuclear group cursor-pointer"
                    whileHover={{ scale: 1.03 }}
                    transition={{ duration: 0.2 }}
                  >
                    <div className="aspect-video relative">
                      <img
                        src={thumb.src}
                        alt={thumb.alt}
                        className="w-full h-full object-cover"
                        loading="lazy"
                      />
                      <div className="absolute inset-0 border border-transparent group-hover:border-primary/30 rounded-xl transition-colors" />
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          ))}
        </div>
        <Footer />
      </div>
    </div>
  );
};

export default Examples;
