import { THUMBNAILS_ROW1, THUMBNAILS_ROW2, THUMBNAILS_ROW3 } from "@/data/siteData";
import { SectionWrapper, SectionHeader } from "@/components/SectionWrapper";

type ThumbnailItem = { label: string; image?: string };

const ALL_COLORS = [
  // Row 1 (9 items)
  "#FF0000", "#00FF00", "#0000FF", "#FFFF00", "#FF00FF", "#00FFFF", "#FF8800", "#88FF00", "#8800FF",
  // Row 2 (10 items)
  "#FF4444", "#44FF44", "#4444FF", "#FFAA00", "#FF44AA", "#44FFAA", "#AA44FF", "#FFDD44", "#44DDFF", "#DD44FF",
  // Row 3 (9 items)
  "#FF6666", "#66FF66", "#6666FF", "#FFCC66", "#FF66CC", "#66FFCC", "#CC66FF", "#FFEE66", "#66EEFF",
];

const ThumbnailRow = ({ items, direction, speed, colorOffset }: { items: ThumbnailItem[]; direction: "left" | "right"; speed: string; colorOffset: number }) => {
  const doubled = [...items, ...items];
  return (
    <div className="overflow-hidden py-2">
      <div
        className={`flex gap-4 w-max ${direction === "left" ? "animate-marquee-left" : "animate-marquee-right"}`}
        style={{ "--marquee-duration": speed } as React.CSSProperties}
      >
        {doubled.map((item, i) => {
          const originalIndex = i % items.length;
          const color = ALL_COLORS[colorOffset + originalIndex] || "#FFFFFF";
          return (
            <div key={`${item.label}-${i}`} className="relative w-64 md:w-72 rounded-xl overflow-hidden group transition-all duration-300 hover:scale-105" style={{ border: `4px solid ${color}` }}>
              <div className="aspect-video bg-gradient-to-br from-muted to-secondary rounded-xl card-nuclear overflow-hidden">
                {item.image ? (
                  <img src={item.image} alt={item.label} className="absolute inset-0 w-full h-full object-cover" />
                ) : (
                  <div className="absolute inset-0 flex items-center justify-center">
                    <span className="text-muted-foreground/40 font-display text-sm">Thumbnail</span>
                  </div>
                )}
                <div className="absolute inset-0 rounded-xl border border-transparent group-hover:border-primary/20 transition-colors duration-300" />
              </div>
              <div className="absolute top-1 left-1 px-1 text-[10px] font-bold text-black" style={{ backgroundColor: color }}>{`R${colorOffset < 9 ? 1 : colorOffset < 19 ? 2 : 3}-${originalIndex + 1}`}</div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

const ThumbnailShowcase = () => {
  return (
    <SectionWrapper id="thumbnails">
      <SectionHeader title="AI-Generated Thumbnail Examples" subtitle="Every thumbnail below was generated by AntiGeneric AI." />
      <div className="space-y-3">
        <ThumbnailRow items={THUMBNAILS_ROW1} direction="left" speed="25s" colorOffset={0} />
        <ThumbnailRow items={THUMBNAILS_ROW2} direction="right" speed="25s" colorOffset={9} />
        <ThumbnailRow items={THUMBNAILS_ROW3} direction="left" speed="25s" colorOffset={19} />
      </div>
    </SectionWrapper>
  );
};

export default ThumbnailShowcase;
